routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/pages-login', function () {
    return view('auth/login');
});




Route::group(['middleware' => 'auth'], function () {
    Route::get('pages-logout', 'DashboardController@logout');
    Route::get('home', 'DashboardController@index');

    /*Esta línea resuelve todas las otras rutas del CRUD*/
    Route::resource('products', 'ProductController');

    /* Route::get('products', 'ProductController@index')->name('products.index');
    Route::get('products/create', 'ProductController@create')->name('products.create');
    Route::post('products/create', 'ProductController@store')->name('products.store');
    Route::get('products/{product}', 'ProductController@show')->name('products.show'); */
    /*Así lo traemos por el titulo en lugar del id, tambien se modifica la vista */
    /* Route::get('products/{product:title}', 'ProductController@show')->name('products.show'); */
    /* Route::get('products/{product}/edit', 'ProductController@edit')->name('products.edit');
    Route::match(['put','patch'], 'products/{product}', 'ProductController@update')->name('products.update');
    Route::delete('products/{product}', 'ProductController@destroy')->name('products.destroy'); */
    Route::resource('products.carts', 'ProductCartController')->only(['store', 'destroy']);

    /*Para carts */
    Route::resource('carts', 'CartController')->only('index');
    /*Para orders */
    Route::resource('orders', 'OrderController')->only(['create', 'store']);
    /*para procesar la orden*/
    Route::resource('orders.payments', 'OrderPaymentController')->only(['create', 'store']);

});

app/Models/Cart.php
<?php

namespace App\Models;

use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    use HasFactory;
    public function products()
    {
        //cuando se accede la clase producto que nos traiga el elemento quantity con Withpivot
        return $this->morphToMany(Product::class, 'productable')->withPivot('quantity');
    }

    //Funcion para calcular el totales, utilizando el pluck
    public function getTotalAttribute()
    {
        return $this->products->pluck('total')->sum();
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Services\CartService;
use App\Models\Cart;
use Illuminate\Http\Request;


class CartController extends Controller
{
    public $cartService;

    public function __construct(CartService $cartService)
    {
        $this->cartService = $cartService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /* $cart = $this->cartService->getFromCookieOrCreate(); */

        return view('carts.index')->with([
            'cart' => $this->cartService->getFromCookie(),
        ]);
    }

}

resources/views/carts/index.blade.php
@extends('layouts.master')

@section('css')

@endsection

@section('breadcrumb')
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Minton</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div>
            <h4 class="page-title">Tu carrito</h4>
        </div>
    </div>
</div>
<!-- end page title -->
@endsection

@section('content')
<div class="row">
    <div class="col">
        <div class="card-box">
           {{--  si no esta establecido cart  o si el contador de productos es vacio --}}
            @if (!isset($cart) || $cart->products->isEmpty())
                <div class="alert alert-warning">
                    Tu carrito esta vacio
                </div>
            @else
            <h4 class="text-center mb-4"><strong>Total: {{ $cart->total }}</strong></h4>
            <a class="btn btn-success mb-3" href="{{ route('orders.create') }}">Empezar orden</a>
            <div class="row">
                @foreach ($cart->products as $product) 
                <div class="col-3">
                 @include('components.product-card')
                </div>
                @endforeach
            </div>
             
            @endempty
            
        </div>
    </div><!-- end col -->
</div>
@endsection

@section('script')

@endsection

@section('script-bottom')
<!-- init js -->

@endsection