routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/pages-login', function () {
    return view('auth/login');
});




Route::group(['middleware' => 'auth'], function () {
    Route::get('pages-logout', 'DashboardController@logout');
    Route::get('home', 'DashboardController@index');

    /*Esta línea resuelve todas las otras rutas del CRUD*/
    Route::resource('products', 'ProductController');

    /* Route::get('products', 'ProductController@index')->name('products.index');
    Route::get('products/create', 'ProductController@create')->name('products.create');
    Route::post('products/create', 'ProductController@store')->name('products.store');
    Route::get('products/{product}', 'ProductController@show')->name('products.show'); */
    /*Así lo traemos por el titulo en lugar del id, tambien se modifica la vista */
    /* Route::get('products/{product:title}', 'ProductController@show')->name('products.show'); */
    /* Route::get('products/{product}/edit', 'ProductController@edit')->name('products.edit');
    Route::match(['put','patch'], 'products/{product}', 'ProductController@update')->name('products.update');
    Route::delete('products/{product}', 'ProductController@destroy')->name('products.destroy'); */
    Route::resource('products.carts', 'ProductCartController')->only(['store', 'destroy']);

    /*Para carts */
    Route::resource('carts', 'CartController')->only('index');
    /*Para orders */
    Route::resource('orders', 'OrderController')->only(['create', 'store']);
    /*para procesar la orden*/
    Route::resource('orders.payments', 'OrderPaymentController')->only(['create', 'store']);

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Canvab - Responsive Bootstrap 4 Admin Dashboard</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @include('layouts.head')
    <style>
        .danger {
            color: red;
        }
    </style>
</head>

<body>
    @yield('content')
    @include('layouts.footer-script')
</body>

</html>

resources/views/layouts/footer-script.blade.php
<script src="{{ URL::asset('assets/js/vendor.min.js') }}"></script>

@yield('script')

<script src="{{ URL::asset('assets/js/app.min.js') }}"></script>

<script>
    var now_url = window.location.href;
    var array = now_url.split("/");
    var my_item_index = array.length - 1;
    if (array[my_item_index] == 'layouts-sidebar-sm') {
        document.body.setAttribute('class', '');
        document.body.classList.add('left-side-menu-sm');
    } else if (array[my_item_index] == 'layouts-dark-sidebar') {
        document.body.setAttribute('class', '');
        document.body.classList.add('left-side-menu-dark');
    } else if (array[my_item_index] == 'layouts-light-topbar') {
        document.body.setAttribute('class', '');
        document.body.classList.add('left-side-menu-dark');
        document.body.classList.add('topbar-light');
    } else if (array[my_item_index] == 'layouts-sidebar-collapsed') {
        document.body.setAttribute('class', '');
        document.body.classList.add('enlarged');
    } else if (array[my_item_index] == 'layouts-boxed') {
        document.body.setAttribute('class', '');
        document.body.classList.add('enlarged');
        document.body.classList.add('boxed-layout');
    } else {

    }

    function preloader_fun() {
        document.getElementById("if_need_loader").style.display = "block";
        document.getElementById("preloader").style.display = "block";
        document.getElementById("status").style.display = "block";
        setTimeout(function() {
            document.getElementById("if_need_loader").style.display = "none";
        }, 1500);
    }
</script>

@yield('script-bottom')

resources/views/layouts/footer.blade.php
<!-- end Footer -->
<footer class="footer">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6">
				{{date('Y') - 1}} - {{ date('Y') }} &copy; 
			</div>
			<div class="col-md-6">
				<div class="text-md-right footer-links d-none d-sm-block">
					<a href="javascript:void(0);">About Us</a>
					<a href="javascript:void(0);">Help</a>
					<a href="javascript:void(0);">Contact Us</a>
				</div>
			</div>
		</div>
	</div>
</footer>

resources/views/layouts/head.blade.php
<link rel="shortcut icon" href="{{ URL::asset('assets/images/favicon.png') }}">

@yield('css')

<!-- App css -->
<link href="{{ URL::asset('assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/app.min.css') }}" rel="stylesheet" type="text/css" />

resources/views/layouts/header.blade.php
   <!-- Topbar Start -->
   <div class="navbar-custom">
       <ul class="list-unstyled topnav-menu float-right mb-0">

           <li class="d-none d-sm-block">
               <form class="app-search">
                   <div class="app-search-box">
                       <div class="input-group">
                           <input type="text" class="form-control" placeholder="Search...">
                           <div class="input-group-append">
                               <button class="btn" type="submit">
                                   <i class="fe-search"></i>
                               </button>
                           </div>
                       </div>
                   </div>
               </form>
           </li>

         

           <li class="dropdown notification-list">
               <a class="nav-link dropdown-toggle  waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                   <i class="fe-bell noti-icon"></i>
                   <span class="badge badge-danger rounded-circle noti-icon-badge">4</span>
               </a>
               <div class="dropdown-menu dropdown-menu-right dropdown-lg">

                   <!-- item-->
                   <div class="dropdown-item noti-title">
                       <h5 class="m-0">
                           <span class="float-right">
                               <a href="" class="text-dark">
                                   <small>Clear All</small>
                               </a>
                           </span>Notification
                       </h5>
                   </div>

                   <div class="slimscroll noti-scroll">

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item active">
                           <div class="notify-icon bg-soft-primary text-primary">
                               <i class="mdi mdi-comment-account-outline"></i>
                           </div>
                           <p class="notify-details">Doug Dukes commented on Admin Dashboard
                               <small class="text-muted">1 min ago</small>
                           </p>
                       </a>

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item">
                           <div class="notify-icon">
                               <img src="{{ URL::asset('assets/images/users/avatar-2.jpg') }}" class="img-fluid rounded-circle" alt="" /> </div>
                           <p class="notify-details">Mario Drummond</p>
                           <p class="text-muted mb-0 user-msg">
                               <small>Hi, How are you? What about our next meeting</small>
                           </p>
                       </a>

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item">
                           <div class="notify-icon">
                               <img src="{{ URL::asset('assets/images/users/avatar-4.jpg') }}" class="img-fluid rounded-circle" alt="" /> </div>
                           <p class="notify-details">Karen Robinson</p>
                           <p class="text-muted mb-0 user-msg">
                               <small>Wow ! this admin looks good and awesome design</small>
                           </p>
                       </a>

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item">
                           <div class="notify-icon bg-soft-warning text-warning">
                               <i class="mdi mdi-account-plus"></i>
                           </div>
                           <p class="notify-details">New user registered.
                               <small class="text-muted">5 hours ago</small>
                           </p>
                       </a>

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item">
                           <div class="notify-icon bg-info">
                               <i class="mdi mdi-comment-account-outline"></i>
                           </div>
                           <p class="notify-details">Caleb Flakelar commented on Admin
                               <small class="text-muted">4 days ago</small>
                           </p>
                       </a>

                       <!-- item-->
                       <a href="javascript:void(0);" class="dropdown-item notify-item">
                           <div class="notify-icon bg-secondary">
                               <i class="mdi mdi-heart"></i>
                           </div>
                           <p class="notify-details">Carlos Crouch liked
                               <b>Admin</b>
                               <small class="text-muted">13 days ago</small>
                           </p>
                       </a>
                   </div>

                   <!-- All-->
                   <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                       View all
                       <i class="fi-arrow-right"></i>
                   </a>

               </div>
           </li>

           <li class="dropdown notification-list">
               <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                   <img src="{{ URL::asset('assets/images/user-comment.jpg') }}" alt="user-image" class="rounded-circle">
                   <span class="pro-user-name ml-1">
                   {{ Auth::user()->name }} <i class="mdi mdi-chevron-down"></i>
                   </span>
               </a>
               <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                   <!-- item-->
                   <div class="dropdown-header noti-title">
                       <h6 class="text-overflow m-0">Welcome !</h6>
                   </div>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item notify-item">
                       <i class="remixicon-account-circle-line"></i>
                       <span>My Account</span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item notify-item">
                       <i class="remixicon-settings-3-line"></i>
                       <span>Settings</span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item notify-item">
                       <i class="remixicon-wallet-line"></i>
                       <span>My Wallet <span class="badge badge-success float-right">3</span> </span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item notify-item">
                       <i class="remixicon-lock-line"></i>
                       <span>Lock Screen</span>
                   </a>

                   <div class="dropdown-divider"></div>

                   <!-- item-->
                   <a href="/pages-logout" class="dropdown-item notify-item">
                       <i class="remixicon-logout-box-line"></i>
                       <span>Logout</span>
                   </a>

               </div>
           </li>


           <li class="dropdown notification-list">
               <a href="javascript:void(0);" class="nav-link right-bar-toggle waves-effect waves-light">
                   <i class="fe-settings noti-icon"></i>
               </a>
           </li>


       </ul>

       <!-- LOGO -->
       <div class="logo-box">
           <a href="index" class="logo text-center">
               <span class="logo-lg">
                   <img src="{{ URL::asset('assets/images/logo1.png') }}" alt="" height="20">
                   <!-- <span class="logo-lg-text-light">Xeria</span> -->
               </span>
               <span class="logo-sm">
                   <!-- <span class="logo-sm-text-dark">X</span> -->
                   <img src="{{ URL::asset('assets/images/apple-touch-icon-114x114.png') }}" alt="" height="24">
               </span>
           </a>
       </div>

       <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
           <li>
               <button class="button-menu-mobile waves-effect waves-light">
                   <i class="fe-menu"></i>
               </button>
           </li>

           <li class="dropdown d-none d-lg-block">
               <a class="nav-link dropdown-toggle waves-effect waves-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                   Create New
                   <i class="mdi mdi-chevron-down"></i>
               </a>
               <div class="dropdown-menu">
                   <!-- item-->
                   <a href="{{route('products.create')}}" class="dropdown-item">
                       <i class="fe-briefcase mr-1"></i>
                       <span>New Product</span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item">
                       <i class="fe-user mr-1"></i>
                       <span>Create Users</span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item">
                       <i class="fe-bar-chart-line- mr-1"></i>
                       <span>Revenue Report</span>
                   </a>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item">
                       <i class="fe-settings mr-1"></i>
                       <span>Settings</span>
                   </a>

                   <div class="dropdown-divider"></div>

                   <!-- item-->
                   <a href="javascript:void(0);" class="dropdown-item">
                       <i class="fe-headphones mr-1"></i>
                       <span>Help & Support</span>
                   </a>

               </div>
           </li>
           <li class="nav-link">
               {{-- inyectamos la dependencia de cartservice directamente en la vista --}}
               @inject('cartService', 'App\Services\CartService')
               <a href="{{ route('carts.index') }}">Carrito de compras ({{ $cartService->countProducts() }})</a>
           </li>

          
       </ul>
   </div>
   <!-- end Topbar -->

resources/views/layouts/master-blank.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Curso Laravel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Panel Curso" name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @include('layouts.head')
    <style>
        .danger {
            color: red;
        }
    </style>
</head>

<body>
    @yield('content')
    @include('layouts.footer-script')
</body>

</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Curso Laravel</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta content="Panel Curso" name="description" />
  <meta content="Coderthemes" name="author" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  @include('layouts.head')

</head>

<body>

  <div id="if_need_loader" style="display:none;">
    <div id="preloader">
      <div id="status">
        <div class="bouncingLoader">
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>

  <div id="wrapper">

    @include('layouts.header')
    @include('layouts.sidebar')

    <div class="content-page">
      <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">

          @yield('breadcrumb')
          @yield('content')
        </div>
      </div>

      @include('layouts.footer')
    </div>
  </div>

  @include('layouts.rightbar')

  @include('layouts.footer-script')
</body>

</html>

resources/views/layouts/rightbar.blade.php
        <!-- Right Sidebar -->
        <div class="right-bar">
            <div class="rightbar-title">
                <a href="javascript:void(0);" class="right-bar-toggle float-right">
                    <i class="fe-x noti-icon"></i>
                </a>
                <h4 class="m-0 text-white">Settings</h4>
            </div>
            <div class="slimscroll-menu">
                <!-- User box -->
                <div class="user-box">
                    <div class="user-img">
                        <img src="assets/images/users/avatar-1.jpg" alt="user-img" title="Mat Helme" class="rounded-circle img-fluid">
                        <a href="javascript:void(0);" class="user-edit"><i class="mdi mdi-pencil"></i></a>
                    </div>

                    <h5><a href="javascript: void(0);">{{ Auth::user()->name }}</a> </h5>
                    <p class="text-muted mb-0"><small>{{ Auth::user()->email }}</small></p>
                </div>
            </div> <!-- end slimscroll-menu-->
        </div>
        <!-- /Right-bar -->

        <!-- Right bar overlay-->
        <div class="rightbar-overlay"></div>

resources/views/layouts/sidebar.blade.php
   <!-- ========== Left Sidebar Start ========== -->
   <div class="left-side-menu">

       <div class="slimscroll-menu">

           <!--- Sidemenu -->
           <div id="sidebar-menu">

               <ul class="metismenu" id="side-menu">

                   <li class="menu-title">Navigation</li>

                   <li>
                       <a href="javascript: void(0);" class="waves-effect">
                           <i class="remixicon-dashboard-line"></i>
                           <span class="badge badge-success badge-pill float-right">2</span>
                           <span> Dashboards </span>
                       </a>
                       <ul class="nav-second-level" aria-expanded="false">
                        <li> 
                            <a href="{{('home')}}">Home</a>
                        </li>
                           <li>
                               <a href="{{route('products.index')}}">Products</a>
                           </li>
                           
                       </ul>
                   </li>

                   
               </ul>

           </div>
           <!-- End Sidebar -->

           <div class="clearfix"></div>

       </div>
       <!-- Sidebar -left -->

   </div>
   <!-- Left Sidebar End -->