routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/pages-login', function () {
    return view('auth/login');
});




Route::group(['middleware' => 'auth'], function () {
    Route::get('pages-logout', 'DashboardController@logout');
    Route::get('home', 'DashboardController@index');

    /*Esta línea resuelve todas las otras rutas del CRUD*/
    Route::resource('products', 'ProductController');

    /* Route::get('products', 'ProductController@index')->name('products.index');
    Route::get('products/create', 'ProductController@create')->name('products.create');
    Route::post('products/create', 'ProductController@store')->name('products.store');
    Route::get('products/{product}', 'ProductController@show')->name('products.show'); */
    /*Así lo traemos por el titulo en lugar del id, tambien se modifica la vista */
    /* Route::get('products/{product:title}', 'ProductController@show')->name('products.show'); */
    /* Route::get('products/{product}/edit', 'ProductController@edit')->name('products.edit');
    Route::match(['put','patch'], 'products/{product}', 'ProductController@update')->name('products.update');
    Route::delete('products/{product}', 'ProductController@destroy')->name('products.destroy'); */
    Route::resource('products.carts', 'ProductCartController')->only(['store', 'destroy']);

    /*Para carts */
    Route::resource('carts', 'CartController')->only('index');
    /*Para orders */
    Route::resource('orders', 'OrderController')->only(['create', 'store']);
    /*para procesar la orden*/
    Route::resource('orders.payments', 'OrderPaymentController')->only(['create', 'store']);

});

app/Models/Order.php
<?php

namespace App\Models;

use App\Models\Payment; //importamos la clase Payment del modelo
use App\Models\User; //importamos la clase de User de su modelo
use App\Models\Product; //importamos la definicion de product
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'status',
        'customer_id', //agregar el customer_id
    ];

    // Relacionamos el pago con, una order tiene un pago, Order tiene un payment
    public function payment()
    {
        return $this->hasOne(Payment::class);
    }

    /*Relacionamos el order con el usuario, order pertenece a un usuario
    tambien indicamos el nombre de la clave foranea en caso de errores, en este caso indicamos
    que es customer_id para identificarla*/
    public function user(){
        return $this->belongsTo(User::class, 'customer_id');
    }

    public function products()
    {
        //cuando se accede la clase producto que nos traiga el elemento quantity con Withpivot
        return $this->morphToMany(Product::class, 'productable')->withPivot('quantity');
    }

      //Funcion para calcular el totales
      public function getTotalAttribute()
      {
          return $this->products->pluck('total')->sum();
      }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Services\CartService;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    
    public $cartService;

    public function __construct(CartService $cartService)
    {
        $this->cartService = $cartService;
        //verificamos si hay un usuario protegiendo la ruta
        $this->middleware('auth');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cart = $this->cartService->getFromCookie();

        if(!isset($cart) || $cart->products->isEmpty()){
            return redirect()
            ->back()
            ->withErrors("El carrito esta vacio");
        }

        return view('orders.create')->with([
            'cart' => $cart,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

     //creamos una orden y la asociamos al usuario
    public function store(Request $request)
    {
         $user = $request->user();

        $order = $user->orders()->create([
            'status' => 'pending',
        ]);
            //ahora pasamos la orden de la cookie a la BD, el cart viene del cartservice
            $cart = $this->cartService->getFromCookie();

            //construimos la lista de id con sus variables, la asignamos en la variable cartproduct
            //luego el elemento element va mapeando los productos
            $cartProductsWithQuantity = $cart->products->mapWithKeys(function ($product){
                $element[$product->id] = ['quantity' => $product->pivot->quantity];

                return $element;
            });


            $order->products()->attach($cartProductsWithQuantity->toArray());

            return redirect()->route('orders.payments.create', ['order' => $order]);
    }

}

resources/views/orders/create.blade.php
@extends('layouts.master')
@section('content')

@section('breadcrumb')
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Products</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div>
            <h4 class="page-title">Detalles de la orden</h4>
            <h5 class="text-center mb-4"><strong>Total de la orden: {{ $cart->total}} </strong></h5>

            <div class="text-center mb-3">
                <form class="d-inline" method="POST" action="{{ route('orders.store') }}">
                    @csrf
                    <button class="btn btn-success" type="submit">Confirmar orden</button>
                </form>
            </div>
            
        </div>
    </div>
</div>
<!-- end page title -->
@endsection

    

    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-light">
            <tr>
                <th>
                   Producto
                </th>
                <th>
                    Precio
                </th>
                <th>
                    Cantidad
                </th>
                <th>Total</th>
               
            </tr>    
            <thead>
                <tbody>
                    @foreach ($cart->products as $product)
                    <tr>

                        <td>
                            <img width="100" src="{{ asset($product->images->first()->path) }}">
                            {{ $product->title }}</td>
                        <td>{{ $product->price }}</td>
                        <td>{{ $product->pivot->quantity }}</td>
                        <td>
                            <strong>
                                ${{ $product->total }}
                            </strong>
                        </td>
                       

                    </tr>
                    @endforeach
                </tbody>
        </table>
    </div>
    <script type="text/javascript">
        function confirmarEliminar() {
            var x = confirm("¿Deseas eliminar este producto?");
            if (x)
                return true;
            else
                return false;
        }
        </script>
@endsection